#!/usr/bin/env bash
# =============================================================================
# CWP AI Agent Plugin - Installer
# =============================================================================
# Installs the CWP CLI tool, shell completions, MCP dependencies, and
# creates the default configuration file.
# =============================================================================
set -euo pipefail

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly PLUGIN_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
readonly VERSION="1.0.0"

# Colors
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BOLD='\033[1m'; NC='\033[0m'

log_info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }
die()       { log_error "$@"; exit 1; }

# ---------------------------------------------------------------------------
# Banner
# ---------------------------------------------------------------------------
echo -e "${BOLD}"
cat <<'EOF'
  ____ ____   ____
 / ___|  _ \ / ___|
| |   | |_) | |  _
| |___|  __/| |_| |
 \____|_|    \____|

  AI Agent Plugin Installer v1.0.0
EOF
echo -e "${NC}"

# ---------------------------------------------------------------------------
# Prerequisite checks
# ---------------------------------------------------------------------------
check_prerequisites() {
    log_info "Checking prerequisites..."

    local missing=()

    command -v bash &>/dev/null || missing+=("bash")
    command -v curl &>/dev/null || missing+=("curl")
    command -v ssh &>/dev/null || missing+=("ssh")

    # bash version check (need 4+)
    local bash_major="${BASH_VERSINFO[0]}"
    if [[ "$bash_major" -lt 4 ]]; then
        die "Bash 4+ required. Found: ${BASH_VERSION}"
    fi

    if [[ ${#missing[@]} -gt 0 ]]; then
        die "Missing required tools: ${missing[*]}"
    fi

    # Optional tools
    if ! command -v jq &>/dev/null; then
        log_warn "jq not found. JSON output will be limited."
        log_warn "Install with: yum install jq (or dnf install jq)"
    fi

    if ! command -v node &>/dev/null; then
        log_warn "Node.js not found. MCP server will not be available."
    fi

    log_info "Prerequisites OK."
}

# ---------------------------------------------------------------------------
# Install CLI
# ---------------------------------------------------------------------------
install_cli() {
    log_info "Installing CWP CLI..."

    local install_dir="/usr/local/bin"
    local completion_bash_dir="/etc/bash_completion.d"
    local completion_zsh_dir="/usr/local/share/zsh/site-functions"

    # Install main CLI script
    cp "${PLUGIN_ROOT}/cli/cwp" "${install_dir}/cwp"
    chmod 755 "${install_dir}/cwp"
    log_info "CLI installed to ${install_dir}/cwp"

    # Install bash completion
    if [[ -d "$completion_bash_dir" ]]; then
        cp "${PLUGIN_ROOT}/cli/cwp-completion.bash" "${completion_bash_dir}/cwp"
        chmod 644 "${completion_bash_dir}/cwp"
        log_info "Bash completion installed to ${completion_bash_dir}/cwp"
    else
        mkdir -p "${completion_bash_dir}"
        cp "${PLUGIN_ROOT}/cli/cwp-completion.bash" "${completion_bash_dir}/cwp"
        chmod 644 "${completion_bash_dir}/cwp"
        log_info "Bash completion installed to ${completion_bash_dir}/cwp"
    fi

    # Install zsh completion
    if [[ -d "$completion_zsh_dir" ]] || command -v zsh &>/dev/null; then
        mkdir -p "$completion_zsh_dir"
        cp "${PLUGIN_ROOT}/cli/cwp-completion.zsh" "${completion_zsh_dir}/_cwp"
        chmod 644 "${completion_zsh_dir}/_cwp"
        log_info "Zsh completion installed to ${completion_zsh_dir}/_cwp"
    fi

    # Make scripts executable
    chmod 755 "${PLUGIN_ROOT}/scripts/"*.sh
    log_info "Script permissions set."
}

# ---------------------------------------------------------------------------
# Setup config
# ---------------------------------------------------------------------------
setup_config() {
    local config_file="$HOME/.cwp-cli.conf"

    if [[ -f "$config_file" ]]; then
        log_warn "Config file already exists: $config_file"
        read -rp "Overwrite? (y/N): " confirm
        if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
            log_info "Keeping existing config."
            return
        fi
    fi

    local gen_date
    gen_date=$(date -u +%Y-%m-%dT%H:%M:%SZ)
    cat > "$config_file" <<CONF
# CWP CLI Configuration
# Generated by installer on ${gen_date}
# Edit these values or run: cwp setup

CWP_HOST=""
CWP_API_KEY=""
CWP_API_PORT="2304"
SSH_USER="root"
SSH_PORT="22"
SSH_KEY=""
CONF
    chmod 600 "$config_file"
    log_info "Config template created: $config_file"
    log_info "Run 'cwp setup' to configure your server details."
}

# ---------------------------------------------------------------------------
# Install MCP dependencies (optional)
# ---------------------------------------------------------------------------
install_mcp_deps() {
    if ! command -v node &>/dev/null; then
        log_warn "Node.js not found. Skipping MCP dependencies."
        return
    fi

    if [[ -f "${PLUGIN_ROOT}/package.json" ]]; then
        log_info "Installing Node.js dependencies..."
        cd "$PLUGIN_ROOT"
        npm install --production 2>/dev/null || log_warn "npm install failed. Run manually if needed."
        cd - >/dev/null
    fi
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
main() {
    check_prerequisites
    install_cli
    setup_config
    install_mcp_deps

    echo ""
    echo -e "${GREEN}${BOLD}Installation complete!${NC}"
    echo ""
    echo "Next steps:"
    echo "  1. Run 'cwp setup' to configure your server"
    echo "  2. Run 'cwp --help' to see all commands"
    echo "  3. Run 'cwp status' to test your connection"
    echo ""
    echo "Documentation: ${PLUGIN_ROOT}/README.md"
}

main "$@"
