#!/usr/bin/env bash
# =============================================================================
# CWP AI Agent Plugin - Interactive Setup Wizard
# =============================================================================
# Prompts for server details, writes config, and tests the connection.
# =============================================================================
set -euo pipefail

readonly CONFIG_FILE="${CWP_CLI_CONF:-$HOME/.cwp-cli.conf}"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

log_info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }
log_step()  { echo -e "\n${CYAN}${BOLD}>>> $*${NC}"; }

# Default values
HOST=""
API_KEY=""
API_PORT="2304"
SSH_USER="root"
SSH_PORT="22"
SSH_KEY=""

# ---------------------------------------------------------------------------
# Banner
# ---------------------------------------------------------------------------
echo -e "${BOLD}${BLUE}"
cat <<'EOF'
  ____ ____   ____
 / ___|  _ \ / ___|
| |   | |_) | |  _
| |___|  __/| |_| |
 \____|_|    \____|

  Interactive Setup Wizard
EOF
echo -e "${NC}"

# ---------------------------------------------------------------------------
# Step 1: Server details
# ---------------------------------------------------------------------------
log_step "Step 1: Server Connection Details"

read -rp "CWP Server hostname or IP address: " HOST
while [[ -z "$HOST" ]]; do
    echo -e "${RED}Host cannot be empty.${NC}"
    read -rp "CWP Server hostname or IP address: " HOST
done

read -rp "SSH port [${SSH_PORT}]: " input
SSH_PORT="${input:-$SSH_PORT}"

read -rp "SSH username [${SSH_USER}]: " input
SSH_USER="${input:-$SSH_USER}"

read -rp "SSH key file path (leave empty for password auth): " input
SSH_KEY="${input:-$SSH_KEY}"

# ---------------------------------------------------------------------------
# Step 2: Test SSH connection
# ---------------------------------------------------------------------------
log_step "Step 2: Testing SSH Connection"

ssh_cmd=("ssh" "-o" "StrictHostKeyChecking=accept-new" "-o" "ConnectTimeout=10" "-o" "BatchMode=yes")
[[ -n "$SSH_KEY" ]] && ssh_cmd+=("-i" "$SSH_KEY")
ssh_cmd+=("-p" "$SSH_PORT" "${SSH_USER}@${HOST}")

echo "Connecting to ${SSH_USER}@${HOST}:${SSH_PORT}..."

if "${ssh_cmd[@]}" "echo 'Connection successful'" 2>/dev/null; then
    log_info "SSH connection successful!"
else
    log_warn "SSH connection failed. This could be due to:"
    echo "  - Wrong hostname/IP"
    echo "  - Wrong port"
    echo "  - SSH key not authorized"
    echo "  - Server not accepting password auth"
    echo ""
    read -rp "Continue setup anyway? (y/N): " cont
    if [[ "$cont" != "y" && "$cont" != "Y" ]]; then
        echo "Setup aborted. Fix SSH access and try again."
        exit 1
    fi
fi

# ---------------------------------------------------------------------------
# Step 3: API configuration
# ---------------------------------------------------------------------------
log_step "Step 3: CWP API Configuration"

echo "The CWP API key can be found in:"
echo "  CWP Admin -> API Manager -> API Key"
echo ""
read -rp "CWP API Key: " API_KEY

read -rp "CWP API port [${API_PORT}]: " input
API_PORT="${input:-$API_PORT}"

# Test API if key provided
if [[ -n "$API_KEY" ]]; then
    echo "Testing API connection..."
    api_response=$(curl -sS --max-time 10 \
        -H "Authorization: Bearer ${API_KEY}" \
        "https://${HOST}:${API_PORT}/v1/test" 2>&1) || true

    if echo "$api_response" | grep -qi "success\|ok\|true" 2>/dev/null; then
        log_info "API connection successful!"
    else
        log_warn "API test inconclusive. Response: ${api_response:0:100}"
        echo "This may be normal if the API uses a different endpoint format."
    fi
fi

# ---------------------------------------------------------------------------
# Step 4: Optional settings
# ---------------------------------------------------------------------------
log_step "Step 4: Optional Settings"

echo "Configure optional notification settings (leave empty to skip):"
read -rp "Notification email (for alerts): " notify_email
read -rp "Webhook URL (for Slack/Discord): " webhook_url

# ---------------------------------------------------------------------------
# Step 5: Write configuration
# ---------------------------------------------------------------------------
log_step "Step 5: Saving Configuration"

cat > "$CONFIG_FILE" <<EOF
# CWP CLI Configuration
# Generated by setup wizard on $(date -u +%Y-%m-%dT%H:%M:%SZ)

CWP_HOST="${HOST}"
CWP_API_KEY="${API_KEY}"
CWP_API_PORT="${API_PORT}"
SSH_USER="${SSH_USER}"
SSH_PORT="${SSH_PORT}"
SSH_KEY="${SSH_KEY}"

# Optional settings
NOTIFY_EMAIL="${notify_email:-}"
WEBHOOK_URL="${webhook_url:-}"
EOF

chmod 600 "$CONFIG_FILE"
log_info "Configuration saved to $CONFIG_FILE"

# ---------------------------------------------------------------------------
# Step 6: Verify installation
# ---------------------------------------------------------------------------
log_step "Step 6: Verify Installation"

if command -v cwp &>/dev/null; then
    log_info "CWP CLI found in PATH: $(command -v cwp)"
else
    log_warn "CWP CLI not in PATH. Run: sudo bash $(dirname "$0")/install.sh"
fi

# Source config for testing
source "$CONFIG_FILE"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo -e "${GREEN}${BOLD}=== Setup Complete ===${NC}"
echo ""
echo "  Server:    ${HOST}"
echo "  SSH:       ${SSH_USER}@${HOST}:${SSH_PORT}"
echo "  API Port:  ${API_PORT}"
echo "  Config:    ${CONFIG_FILE}"
echo ""
echo "Quick start:"
echo "  cwp status              # Check server status"
echo "  cwp user list           # List user accounts"
echo "  cwp service list        # List services"
echo "  cwp --help              # Show all commands"
echo ""
echo -e "${BOLD}Happy managing!${NC}"
